export const MOCK_JOURNALS = [
  {
    _id: "m1",
    title: "Building a Real-World Web Application During Our Internship",
    excerpt: "Our interns built a full-stack web application from scratch using React, Node.js and MongoDB. Here's how we planned, designed and deployed our project successfully.",
    content: "<p>Our interns built a full-stack web application from scratch using React, Node.js and MongoDB. Here's how we planned, designed and deployed our project successfully.</p><p>We started by planning the architecture and then moved on to the design phase. Finally, we deployed the application to a cloud server.</p>",
    category: "Projects",
    author: "Inetz Team",
    date: "2026-08-08T00:00:00.000Z",
    readTime: "6 min read",
    isFeatured: true,
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&q=80&w=800",
  },
  {
    _id: "m2",
    title: "SEO Workshop: Keyword Research to Ranking",
    excerpt: "Learn how we conducted a comprehensive SEO workshop for our interns, covering keyword research, on-page optimization, and link building.",
    content: "<p>Learn how we conducted a comprehensive SEO workshop for our interns, covering keyword research, on-page optimization, and link building.</p>",
    category: "Data Science",
    author: "Inetz Team",
    date: "2026-08-06T00:00:00.000Z",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&q=80&w=600",
  },
  {
    _id: "m3",
    title: "Full-Stack E-Commerce Website Development (MERN Stack)",
    excerpt: "Building a fully functional e-commerce website using the MERN stack. A deep dive into the technologies and processes used.",
    content: "<p>Building a fully functional e-commerce website using the MERN stack. A deep dive into the technologies and processes used.</p>",
    category: "Projects",
    author: "Inetz Team",
    date: "2026-08-05T00:00:00.000Z",
    readTime: "6 min read",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=600",
  },
  {
    _id: "m4",
    title: "Interns Talk: Our Experience So Far in Java Training",
    excerpt: "Our interns share their experiences and key takeaways from the intensive Java training program.",
    content: "<p>Our interns share their experiences and key takeaways from the intensive Java training program.</p>",
    category: "Java Full Stack",
    author: "Inetz Team",
    date: "2026-08-03T00:00:00.000Z",
    readTime: "4 min read",
    videoUrl: "yes",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&q=80&w=600",
  },
  {
    _id: "m5",
    title: "Team Building Activities and Office Fun",
    excerpt: "A look back at some of the fun team-building activities and events we hosted for our interns.",
    content: "<p>A look back at some of the fun team-building activities and events we hosted for our interns.</p>",
    category: "Python Full Stack",
    author: "Inetz Team",
    date: "2026-08-01T00:00:00.000Z",
    readTime: "3 min read",
    image: "https://images.unsplash.com/photo-1529333166437-7750a6dd5a70?auto=format&fit=crop&q=80&w=600",
  },
  {
    _id: "m6",
    title: "AWS Cloud Certifications Earned by Our DevOps Interns",
    excerpt: "Congratulations to our DevOps interns for successfully earning their AWS Cloud Certifications.",
    content: "<p>Congratulations to our DevOps interns for successfully earning their AWS Cloud Certifications.</p>",
    category: "Achievements",
    author: "Inetz Team",
    date: "2026-07-30T00:00:00.000Z",
    readTime: "4 min read",
    image: "https://images.unsplash.com/photo-1523287562758-66c7fc58967f?auto=format&fit=crop&q=80&w=600",
  },
  {
    _id: "m7",
    title: "UI/UX Design Workshop with Figma for Frontend Devs",
    excerpt: "An interactive workshop focusing on UI/UX design principles and practical application using Figma.",
    content: "<p>An interactive workshop focusing on UI/UX design principles and practical application using Figma.</p>",
    category: "MERN Stack",
    author: "Inetz Team",
    date: "2026-07-28T00:00:00.000Z",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?auto=format&fit=crop&q=80&w=600",
  },
  {
    _id: "m8",
    title: "Java Spring Boot API Project Implementation",
    excerpt: "Exploring the development and implementation of robust APIs using Java Spring Boot.",
    content: "<p>Exploring the development and implementation of robust APIs using Java Spring Boot.</p>",
    category: "Projects",
    author: "Inetz Team",
    date: "2026-07-25T00:00:00.000Z",
    readTime: "7 min read",
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&q=80&w=800",
  },
  {
    _id: "m9",
    title: "Python Machine Learning Workshop: From Data to Model",
    excerpt: "A hands-on workshop covering the end-to-end process of building machine learning models using Python.",
    content: "<p>A hands-on workshop covering the end-to-end process of building machine learning models using Python.</p>",
    category: "Python Full Stack",
    author: "Inetz Team",
    date: "2026-07-20T00:00:00.000Z",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&q=80&w=600",
  },
  {
    _id: "m10",
    title: "Interns Cracking Data Science Roles with Python",
    excerpt: "Success stories from our interns who secured data science roles after completing our Python program.",
    content: "<p>Success stories from our interns who secured data science roles after completing our Python program.</p>",
    category: "Achievements",
    author: "Inetz Team",
    date: "2026-07-18T00:00:00.000Z",
    readTime: "4 min read",
    image: "https://images.unsplash.com/photo-1523287562758-66c7fc58967f?auto=format&fit=crop&q=80&w=600",
  },
  {
    _id: "m11",
    title: "Data Structures & Algorithms (DSA) Mastery Hackathon",
    excerpt: "Highlights from our recent DSA hackathon where interns showcased their problem-solving skills.",
    content: "<p>Highlights from our recent DSA hackathon where interns showcased their problem-solving skills.</p>",
    category: "Java Full Stack",
    author: "Inetz Team",
    date: "2026-07-15T00:00:00.000Z",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&q=80&w=600",
  },
  {
    _id: "m12",
    title: "Embedded Systems & IoT Hardware Prototyping",
    excerpt: "An overview of the exciting hardware prototyping projects completed by our interns in the IoT track.",
    content: "<p>An overview of the exciting hardware prototyping projects completed by our interns in the IoT track.</p>",
    category: "Projects",
    author: "Inetz Team",
    date: "2026-07-10T00:00:00.000Z",
    readTime: "6 min read",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=600",
  },
  {
    _id: "m13",
    title: "Advanced DevOps and Docker Deployment Workshop",
    excerpt: "Deep dive into containerization and deployment strategies using Docker and advanced DevOps practices.",
    content: "<p>Deep dive into containerization and deployment strategies using Docker and advanced DevOps practices.</p>",
    category: "Java Full Stack",
    author: "Inetz Team",
    date: "2026-07-05T00:00:00.000Z",
    readTime: "8 min read",
    image: "https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?auto=format&fit=crop&q=80&w=600",
  },
  {
    _id: "m14",
    title: "A Day in the Life of a Tech Intern in Chennai",
    excerpt: "Follow our tech interns as they navigate a typical day of learning, coding, and collaborating in our Chennai office.",
    content: "<p>Follow our tech interns as they navigate a typical day of learning, coding, and collaborating in our Chennai office.</p>",
    category: "MERN Stack",
    author: "Inetz Team",
    date: "2026-07-01T00:00:00.000Z",
    readTime: "4 min read",
    image: "https://images.unsplash.com/photo-1529333166437-7750a6dd5a70?auto=format&fit=crop&q=80&w=600",
  },
  {
    _id: "m15",
    title: "Full-Stack Development Bootcamp Graduation",
    excerpt: "Celebrating the achievements of our interns as they graduate from our intensive Full-Stack Development Bootcamp.",
    content: "<p>Celebrating the achievements of our interns as they graduate from our intensive Full-Stack Development Bootcamp.</p>",
    category: "MERN Stack",
    author: "Inetz Team",
    date: "2026-06-25T00:00:00.000Z",
    readTime: "3 min read",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&q=80&w=600",
  },
  {
    _id: "m16",
    title: "Database Optimization with MongoDB and PostgreSQL",
    excerpt: "Learn the best practices and techniques for optimizing database performance using MongoDB and PostgreSQL.",
    content: "<p>Learn the best practices and techniques for optimizing database performance using MongoDB and PostgreSQL.</p>",
    category: "Data Science",
    author: "Inetz Team",
    date: "2026-06-20T00:00:00.000Z",
    readTime: "5 min read",
    image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&q=80&w=600",
  },
  {
    _id: "m17",
    title: "Building Real-Time Chat Apps with Socket.io (MERN)",
    excerpt: "A detailed guide on how our interns built robust real-time chat applications using Socket.io and the MERN stack.",
    content: "<p>A detailed guide on how our interns built robust real-time chat applications using Socket.io and the MERN stack.</p>",
    category: "Projects",
    author: "Inetz Team",
    date: "2026-06-15T00:00:00.000Z",
    readTime: "7 min read",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=600",
  },
  {
    _id: "m18",
    title: "Interns Placed at Top Tech Companies",
    excerpt: "We are proud to announce that several of our interns have successfully secured placements at top technology companies.",
    content: "<p>We are proud to announce that several of our interns have successfully secured placements at top technology companies.</p>",
    category: "Achievements",
    author: "Inetz Team",
    date: "2026-06-10T00:00:00.000Z",
    readTime: "4 min read",
    image: "https://images.unsplash.com/photo-1523287562758-66c7fc58967f?auto=format&fit=crop&q=80&w=600",
  },
  {
    _id: "m19",
    title: "Weekly Code Reviews and Refactoring Sessions",
    excerpt: "An inside look at our weekly code review processes and how we help interns improve their coding practices.",
    content: "<p>An inside look at our weekly code review processes and how we help interns improve their coding practices.</p>",
    category: "Python Full Stack",
    author: "Inetz Team",
    date: "2026-06-05T00:00:00.000Z",
    readTime: "3 min read",
    image: "https://images.unsplash.com/photo-1529333166437-7750a6dd5a70?auto=format&fit=crop&q=80&w=600",
  },
  {
    _id: "m20",
    title: "Software Engineering Best Practices and Agile",
    excerpt: "Teaching interns the importance of Agile methodologies and applying software engineering best practices in real-world scenarios.",
    content: "<p>Teaching interns the importance of Agile methodologies and applying software engineering best practices in real-world scenarios.</p>",
    category: "Java Full Stack",
    author: "Inetz Team",
    date: "2026-06-01T00:00:00.000Z",
    readTime: "6 min read",
    image: "https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?auto=format&fit=crop&q=80&w=600",
  },
  {
    _id: "m21",
    title: "Our Weekly Friday Fun and Gaming Tournaments",
    excerpt: "Balancing work and play! A recap of our exciting Friday gaming tournaments and team building activities.",
    content: "<p>Balancing work and play! A recap of our exciting Friday gaming tournaments and team building activities.</p>",
    category: "Data Science",
    author: "Inetz Team",
    date: "2026-05-25T00:00:00.000Z",
    readTime: "2 min read",
    image: "https://images.unsplash.com/photo-1529333166437-7750a6dd5a70?auto=format&fit=crop&q=80&w=600",
  },
];
